---
# code: language=ansible


- name: install Extensions | Install VS Code extensions for each user
  become: true
  become_user: "{{ item.0.username }}"
  ansible.builtin.shell: "code --install-extension {{ item.1 }}"
  register: shelloutput
  changed_when: shelloutput.rc != 0
  loop: "{{ extensions_var | subelements('extensions') }}"
  when: item.0.username in (userlist | selectattr('host_name', 'equalto', inventory_hostname) | map(attribute='users') | first)
